spring:
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev

  application:
    name: discovery-service

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/